apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 3 
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
kind: Service 
apiVersion: v1 
metadata: 
  name: auth-service 
spec: 
  selector: 
    app: auth 
  ports: 
  - protocol: TCP 
    port: 5001
    targetPort: 5001
    nodePort: 31001 
  type: NodePort 
