apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-deployment #the name of the deployment
spec:
  selector:
    matchLabels:
      app: shortener #define the behavior of pods which matches this label
  replicas: 3 #the number of replica, according to canvas it should be at least 3
  template:
    metadata:
      labels:
        app: shortener #the label of all pods created from this deployment 
    spec:
      containers:
      - name: shortener #container name
        image: shortener #image name
        imagePullPolicy: Never #no retry when pulling failed
        ports:
        - containerPort: 5000 #the port of the container
---
kind: Service 
apiVersion: v1 
metadata: 
  name: shortener-service 
spec: 
  selector: 
    app: shortener 
  ports: 
  - protocol: TCP 
    port: 5000 #the port that exposes the kubernetes services in the cluster
    targetPort: 5000 #the port that the service will send requests to (pod port)
    nodePort: 31000 #the node that exposes the kubernetes services outside.
  type: NodePort 
